name: Deploy Logistics Management System

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: |
        npm install
        cd server && npm install
        
    - name: Run tests
      run: npm test --if-present
      
    - name: Build frontend
      run: npm run build
      
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      if: github.ref == 'refs/heads/main'
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./build
        
    - name: Create deployment package
      run: |
        mkdir -p deployment
        cp -r server deployment/
        cp -r build deployment/frontend
        cp start.sh deployment/
        cp README.md deployment/
        tar -czf logistics-system.tar.gz deployment/
        
    - name: Upload deployment package
      uses: actions/upload-artifact@v3
      with:
        name: logistics-system
        path: logistics-system.tar.gz


