name: Deploy Supabase SQL

on:
  push:
    branches: [ main ]
    paths:
      - 'supabase/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup psql
        uses: ankane/setup-postgres@v1

      - name: Apply SQL
        env:
          SUPABASE_DB_URL: ${{ secrets.SUPABASE_DB_URL }}
        run: |
          if [ -z "$SUPABASE_DB_URL" ]; then
            echo "Missing SUPABASE_DB_URL secret" && exit 1
          fi
          for f in $(ls -1 supabase/migrations/*.sql | sort); do
            echo "Applying $f";
            psql "$SUPABASE_DB_URL" -v ON_ERROR_STOP=1 -f "$f" || exit 1;
          done


